### ISSUE TITLE
Won't work on iOS 18

### ISSUE THREAD

**Issue by lukyanov** [ShoutSocial/share_handler#102]
The extension is not working on iOS 18.
Could [this change](https://github.com/bhagat-techind/flutter_sharing_intent/commit/302162d0e08c05cb92f32e3583f7a1ef191d1cc7) in another similar extension help?

**Comment by anchao-lu** [comment]
When will the update be on pub.dev?

**Comment by lukyanov** [comment]
> I second that. Not working on iOS 18. Otherwise great work, thank you!
> 
> EDIT: the suggested FIX from @lukyanov fixes the issue. As a quick fix you can override the redirectToHostApp method in your ShareViewController class. with the code mentioned in the link. Thank you!

@RichardRaue Could you let me know how you applied the workaround? I tried this myself and couldn't make it work.

**Comment by gaucidaniel** [comment]
Opened a pull request with the fix discussed above. Until released, the fix can be applied by adding the following to your `pubspec.yaml`:

```
dependency_overrides:
  share_handler_ios:
    git:
      url: https://github.com/gaucidaniel/share_handler.git
      path: share_handler_ios
      ref: main
```
