### ISSUE TITLE
How to use the latest version? I want to use the latest version that has fixed UIApplication.openURL

### ISSUE THREAD

**Issue by FairyWorld** [ShoutSocial/share_handler#99]
How to use the latest version? I want to use the latest version that has fixed UIApplication.openURL
I encountered a similar problem. The ios browser shared URL would crash. I saw that someone had submitted a solution to mr and it was adopted, but the version on pub.dev was still 6 months old.

**Comment by szuwest** [comment]
you have to call the method yourself in application:didFinishLaunchingWithOptions 

if (launchOptions != nil) {
          SwiftShareHandlerIosPlatform.instance.application(application, didFinishLaunchingWithOptions: launchOptions!)
      }

**Comment by JoshJuncker** [comment]
I can't publish to pub.dev right now. Still trying to get permission to do that, or have it transferred. To use main from GitHub, do something like this. 

```
dependency_overrides:
  share_handler_ios:
    git:
      url: https://github.com/ShoutSocial/share_handler
      path: share_handler_ios
  share_handler_android: 
    git:
      url: https://github.com/ShoutSocial/share_handler
      path: share_handler_android
```

```
dependencies:
    share_handler:
      git:
        url: https://github.com/ShoutSocial/share_handler
        path: share_handler
```
